# Generated by Django 4.2 on 2024-05-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_remove_post_body_paragraph"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="date",
        ),
        migrations.RemoveField(
            model_name="post",
            name="title_tag",
        ),
        migrations.AlterField(
            model_name="paragraph",
            name="text",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
