# Generated by Django 4.2 on 2024-05-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_post_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="post_photos/"),
        ),
        migrations.AlterField(
            model_name="paragraph",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="paragraph_photos/"
            ),
        ),
    ]
