# Generated by Django 4.2 on 2024-05-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0008_post_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(upload_to="post_photos/"),
        ),
    ]
